server:
  port: 8080
  servlet:
    context-path: /api

spring:
  datasource:
    username: root
    password: wnh
    url: jdbc:mysql://localhost:3306/user_center
    driver-class-name: com.mysql.cj.jdbc.Driver
  session:
    timeout: 86400

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false
  global-config:
    db-config:
      logic-delete-field: isDelete

